name: "CI - linters and tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: "Install just"
        uses: extractions/setup-just@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5

      - name: "Install dependencies"
        run: uv sync --dev --no-cache-dir --frozen

      - name: "Run ruff"
        run: just ruff

      - name: "Run fawltydeps"
        run: just deps

      - name: "Run mypy"
        run: just mypy

      - name: "Run tests"
        run: just test
